-- Eight-color scheme
local lexers = vis.lexers
-- dark
lexers.STYLE_DEFAULT ='back:#000000,fore:#ffffff'
lexers.STYLE_NOTHING = 'back:#000000'
lexers.STYLE_CLASS = 'fore:#008f11,bold'
lexers.STYLE_COMMENT = 'fore:#202020,italics'
lexers.STYLE_CONSTANT = 'fore:#003b00,bold'
lexers.STYLE_DEFINITION = 'fore:#003b00,bold'
lexers.STYLE_ERROR = 'fore:red,back:#ff0000'
lexers.STYLE_FUNCTION = 'fore:#008f11,bold'
lexers.STYLE_KEYWORD = 'fore:#008f11,bold'
lexers.STYLE_LABEL = 'fore:#eb0028,bold'
lexers.STYLE_NUMBER = 'fore:#80ce87'
lexers.STYLE_OPERATOR = 'fore:#808080,'
lexers.STYLE_REGEX = 'fore:#008f11'
lexers.STYLE_STRING = 'fore:#003b00'
lexers.STYLE_PREPROCESSOR = 'fore:#505050, bold'
lexers.STYLE_TAG = 'fore:#003b00,bold'
lexers.STYLE_TYPE = 'fore:#22b455'
lexers.STYLE_VARIABLE = 'fore:#22b455'
lexers.STYLE_WHITESPACE = ''
lexers.STYLE_EMBEDDED = 'back:#f2ca30,bold'
lexers.STYLE_IDENTIFIER = 'fore:#f0f0f0'

lexers.STYLE_LINENUMBER = 'fore:#003b00'
lexers.STYLE_LINENUMBER_CURSOR = lexers.STYLE_LINENUMBER
lexers.STYLE_CURSOR = 'reverse'
lexers.STYLE_CURSOR_PRIMARY = lexers.STYLE_CURSOR..',fore:#ffffff'
lexers.STYLE_CURSOR_LINE = 'underlined'
lexers.STYLE_COLOR_COLUMN = 'back:red'
lexers.STYLE_SELECTION = 'back:white'
lexers.STYLE_STATUS = 'back:#003b00,fore:#ffffff'
lexers.STYLE_STATUS_FOCUSED = 'back:#003b00,fore:#ffffff,bold'
lexers.STYLE_SEPARATOR = lexers.STYLE_DEFAULT
lexers.STYLE_INFO = 'fore:default,back:default,bold'
lexers.STYLE_EOF = ''
