-- Eight-color scheme
local lexers = vis.lexers
-- dark
lexers.STYLE_DEFAULT ='back:#000000,fore:#f0f0f0'
lexers.STYLE_NOTHING = 'back:#000000'
lexers.STYLE_CLASS = 'fore:#eb0028,bold'
lexers.STYLE_COMMENT = 'fore:#202020,italics'
lexers.STYLE_CONSTANT = 'fore:#f26711,bold'
lexers.STYLE_DEFINITION = 'fore:#eb0028,bold'
lexers.STYLE_ERROR = 'fore:red,back:#f0f0f0'
lexers.STYLE_FUNCTION = 'fore:#eb0028,bold'
lexers.STYLE_KEYWORD = 'fore:#eb0028,bold'
lexers.STYLE_LABEL = 'fore:#eb0028,bold'
lexers.STYLE_NUMBER = 'fore:#f2ca30'
lexers.STYLE_OPERATOR = 'fore:#f0f0f0,'
lexers.STYLE_REGEX = 'fore:#eb0028'
lexers.STYLE_STRING = 'fore:#f26711'
lexers.STYLE_PREPROCESSOR = 'fore:#f2ca30, bold'
lexers.STYLE_TAG = 'fore:red,bold'
lexers.STYLE_TYPE = 'fore:#eb0028'
lexers.STYLE_VARIABLE = 'fore:#eb0028'
lexers.STYLE_WHITESPACE = ''
lexers.STYLE_EMBEDDED = 'back:#f2ca30,bold'
lexers.STYLE_IDENTIFIER = 'fore:white'

lexers.STYLE_LINENUMBER = 'fore:white'
lexers.STYLE_LINENUMBER_CURSOR = lexers.STYLE_LINENUMBER
lexers.STYLE_CURSOR = 'reverse'
lexers.STYLE_CURSOR_PRIMARY = lexers.STYLE_CURSOR..',fore:#ffffff'
lexers.STYLE_CURSOR_LINE = 'underlined'
lexers.STYLE_COLOR_COLUMN = 'back:red'
lexers.STYLE_SELECTION = 'back:white'
lexers.STYLE_STATUS = 'reverse'
lexers.STYLE_STATUS_FOCUSED = 'reverse,bold'
lexers.STYLE_SEPARATOR = lexers.STYLE_DEFAULT
lexers.STYLE_INFO = 'fore:default,back:default,bold'
lexers.STYLE_EOF = ''
